### ISSUE TITLE
Creation of a minimal example

### ISSUE THREAD

**Issue by kolibril13** [12rambau/sphinx-social#3]
I can create a minimal example that can be hosted on GitHub pages.
@12rambau : Can you give me temp. admin rights for this repository, so that I can set up the Sphinx GitHub pages build?

**Comment by 12rambau** [comment]
oh I was using the documenttion for that: https://sphinx-social.readthedocs.io/en/latest/ (build for every PR)

If you think it's not relevant I gave you admin rights

**Comment by 12rambau** [comment]
I checked on the contributor page and it seems for personal repostory (not leaving in an organization), I cannot grant you any more power. The button is simply not there: 

![image](https://user-images.githubusercontent.com/12596392/232086814-b5085c03-3706-4c53-ac9f-7319422de0d4.png)

**Comment by kolibril13** [comment]
Oh, perfect, then we don't need the github pages side, 
thanks for the quick setup!
